cron_interval="20s"
[address_map.juno-testnet]
contract_address = "juno1u2gw57lm4yu9zz572cpv54f9az3xgm6cm3jx3r4d59q5u8avpwdsc8d2wa"
relayer_address = "juno19fxfjvj5qyl9f9hplf5v3vl8zuxhaaveqrx04z"
denom="ujunox"
threshold=10000000000


[network_rpc]
juno-testnet = "https://juno-testnet-api.polkachu.com"