cron_interval="10s"

[address_map.juno-testnet]
contract_address = "juno1v7na2m53cm3rkxxpe0k62yra3nkpeq7dy5zr528795fgymxrlz2ql4jsqp"
relayer_address = "juno1mlaew6aj273mw6j4uhtcvpv7ujjt0zc8az7lre"
denom="ujunox"
warning_threshold=500000000
threshold=10000000000
report_median=true
report_deviation=true

[network_rpc]
juno-testnet = "https://juno-testnet-api.polkachu.com"