cron_interval="30s"

[address_map.juno-testnet]
contract_address = "juno1yqm8q56hjv8sd4r37wdhkkdt3wu45gc5ptrjmd9k0nhvavl0354qwcf249"
relayer_address = "juno1rkhrfuq7k2k68k0hctrmv8efyxul6tgn8hny6y"
denom="ujuno"
warning_threshold=5000000
threshold=1000000

[network_rpc]
juno-testnet = "https://juno-api.polkachu.com"